version: '3.4'

services:
  nh.qhatu.common.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9201:80"

  nh.qhatu.customer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9202:80"

  nh.qhatu.homedelivery.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9203:80"

  nh.qhatu.omnichannel.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9204:80"
  nh.qhatu.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9500:80"
  nh.qhatu.security.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
    ports:
      - "9205:80"

